# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI Build and Test

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  BUILD:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20.x]
        artifact-name: ['integration-artifact']
        
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
     
    - name: setup node
      uses: actions/setup-node@v4
      with: 
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run : |
        npm install
        npm ci
        # npm clean install

    - name: build
      run: |
        npm run build --if-present
        npm run test --if-present

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.node-version }}
        path: ./dist

  DEPLOY-TO-DOCKER-HUB:
    runs-on: ubuntu-22.04
    needs: [BUILD]
    strategy:
      matrix:
        node-version: [20.x]
        repository-name: ['service.order']

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/service.order:latest
      
  
